### ISSUE TITLE
File URL path is not dynamic

### ISSUE THREAD

**Issue by benhaynes** [directus/directus-sdk-php#10]
Files returned by the SDK get an automatic `url` value:

`/storage/uploads/00000000001.png`

But this path (`'/storage/uploads/`) is not pulling from the configuration.php file (might be static)

**Comment by WellingGuzman** [comment]
The issue we still have is that we need to copy the Directus configuration back to the sdk, unless we are using remote connections.

it should work by changing the filesystem `root_url` and `root_thumb_url`

```php
require 'vendor/autoload.php';

$config = [
    'database' => [
        'hostname' => 'localhost',
        'username' => 'root',
        'password' => '123',
        'database' => 'directus_db',
        // Optional
        // 'port' => 3306,
        // 'charset' => 'utf8'
    ],
    'filesystem' => [
        'root' => '/path/to/directus/files/uploads',
        'root_url' => '/files/uploads',
        'root_thumb_url' => '/files/uploads/thumbs'
    ]
];

$client = \Directus\SDK\ClientFactory::create($config);
$files = $client->getFiles();

foreach($files as $file) {
    echo $file->url . '<br>';
}
```

**Comment by WellingGuzman** [comment]
Was the issue solve by my previous snippet? if it didn't let me know and I will re-open this ticket.
