### ISSUE TITLE
composer cannot install directus/sdk

### ISSUE THREAD

**Issue by gaou-piou** [directus/directus-sdk-php#11]
when i type composer update it returns 

Problem 1
    - directus/sdk 0.1.2 requires directus/permissions 0.1.* -> satisfiable by directus/permissions[0.1.0] but these conflict with your requirements or minimum-stability.
    - directus/sdk 0.1.1 requires directus/permissions 0.1.* -> satisfiable by directus/permissions[0.1.0] but these conflict with your requirements or minimum-stability.
    - directus/sdk 0.1.0 requires directus/permissions 0.1.* -> satisfiable by directus/permissions[0.1.0] but these conflict with your requirements or minimum-stability.
    - Installation request for directus/sdk 0.1.* -> satisfiable by directus/sdk[0.1.0, 0.1.1, 0.1.2].

**Comment by WellingGuzman** [comment]
Hey @gaou-piou, which php version are you on? make sure to set the `minimum-stability` to `dev`.

**Comment by gaou-piou** [comment]
minimum-stability is setted to dev

My php version is PHP 5.6.30-0+deb8u1

**Comment by WellingGuzman** [comment]
Thanks, can you show me how you `composer.json` looks like?

**Comment by gaou-piou** [comment]
here it is 
`{
  "require": {
    "php": ">=5.5.0",
    "slim/slim": "2.6.2",
    "slim/extras": "dev-master",
    "twig/twig":  "1.*",
    "directus/migrations": "dev-master",
    "directus/permissions": "0.9.*@dev",
    "directus/database": "~0.1.5",
    "league/flysystem": "^1.0",
    "swiftmailer/swiftmailer": "^5.4",
    "directus/sdk": "0.1.*"
  },
  "require-dev": {
    "phpunit/phpunit": "~3.7.0"
  },
  "suggest": {
    "paragonie/random_compat": "Generates cryptographically more secure pseudo-random bytes"
  },
  "_require": {
    "rackspace/php-opencloud": "dev-master",
    "amazonwebservices/aws-sdk-for-php": "1.6.2",
    "aws/aws-sdk-php": "2.6.*@dev"
  },
  "autoload": {
    "psr-4": {
      "Directus\\": "api/core/Directus/",
      "Directus\\API\\Routes\\": "api/routes/",
      "Directus\\Installation\\": "installation/includes/",
      "Directus\\Embed\\Provider\\": "customs/embeds/"
    },
    "files": [
      "api/core/functions.php"
    ]
  },
  "minimum-stability": "dev",
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/WellingGuzman/Slim-Extras.git"
    },
    {
      "type": "git",
      "url": "https://github.com/wellingguzman/zend-db"
    }
  ]
}`

**Comment by WellingGuzman** [comment]
**I edited your composer.json format**

That's Directus `composer.json`, why are you installing the SDK on a Directus install? you can use the same code from within Directus.

I'm curious to know what are you trying to do.

Also did you run `composer install` or `composer update`?

**Comment by gaou-piou** [comment]
I try to make a registration form.
But now i understand what you say.
You are write.
 informational: how can i use 
```
$client = \Directus\SDK\ClientFactory::create('LdErj4ogsEIqKoxrOfIwen7mUQOz4D9J', [
		// Directus API Path without its version
		'base_url' => 'http://biobebe.mooo.com',
		'version' => '1' // Optional - default 1
	]);
```
fron within Directus?

**Comment by WellingGuzman** [comment]
What I recommend it's creating a separate project and use the SDK, take a look at the web app example https://github.com/directus/webapp-example

**Comment by gaou-piou** [comment]
Thank you very much for your help.
I will

**Comment by WellingGuzman** [comment]
Awesome, let's know how it goes.
