### ISSUE TITLE
Error using PHP SDK

### ISSUE THREAD

**Issue by Sirjoseph94** [directus/directus-sdk-php#12]
I keep getting ` Fatal error: Uncaught Error: Class 'Directus\SDK\ClientFactory' not found in C:\xampp\htdocs\www\admin\call.php:32 Stack trace: #0 {main} thrown in C:\xampp\htdocs\www\admin\call.php on line 32`

require 'vendor/autoload.php';

$client = \Directus\SDK\ClientFactory::create('RNWoWuMiyaTXwWGmUkOWcsHugNcuIUPC', [
    // Directus API Path without its version
    'base_url' => 'http://localhost/admin',
    'version' => '1' // Optional - default 1
]);

$articles = $client->getItems('events');
foreach($articles as $article) {
    echo $article->event_name . '<br>';
}

**Comment by WellingGuzman** [comment]
Hey @Sirjoseph94, how did you install the SDK, this seems like you are missing the SDK package. What's on your `vendor` directory?

**Comment by mbuchser** [comment]
Hello, 
Same Error here, downloaded the directus package from github including the vendor directory with autoload.php, bin,composer,directus, league, slim, swiftmailer, twig, zendframework inside. 

getting the loader seems to work:

// Composer Autoloader
$loader = require 'vendor/autoload.php';
var_dump( $loader);


object(Composer\Autoload\ClassLoader)#1 (10) { ["prefixLengthsPsr4":"Composer\Autoload\ClassLoader":private]=> array(3) { ["Z"]=> array(2) { ["Zend\Stdlib\"]=> int(12) ["Zend\Db\"]=> int(8) } ["L"]=> array(1) { ["League\Flysystem\"]=> int(17) } ["D"]=> array(7) { ["Directus\Permissions\"]=> int(21) ["Directus\Installation\"]=> int(22) ["Directus\Embed\Provider\"]=> int(24) ["Directus\Database\"]=> int(18) ["Directus\Collection\"]=> int(20) ["Directus\API\Routes\"]=> int(20) ["Directus\"]=> int(9) } } ["prefixDirsPsr4":"Composer\Autoload\ClassLoader":private]=> array(10) { ["Zend\Stdlib\"]=> array(1) ………


But then: 
Fatal error: Class 'Directus\SDK\ClientFactory' not found

And if you include them one by one:
include 'Directus/SDK/ClientFactory.php';
include 'Directus/SDK/ClientRemote.php';
include 'Directus/SDK/BaseClientRemote.php';

you get the error at:
Fatal error: Class 'Directus\SDK\BaseClientRemote' not found in /directus/Directus/SDK/ClientRemote.php on line 21

What i can't find in the SDK Directory is:  Directus\Util\ArrayUtils

Which is called in ClientRemote.php (Line 13)

**Comment by WellingGuzman** [comment]
Hey @mbuchser,

How did you install/download the SDK? which branch did you cloned? which tagged version you used?

**Comment by mbuchser** [comment]
Downloaded a zip file from: https://github.com/directus/directus-sdk-php

**Comment by WellingGuzman** [comment]
Thanks for the information, I will give it a look today and see if I could reproduce it.

I will also try it on a windows machine.

**Comment by Sirjoseph94** [comment]
Any update on this please?

**Comment by WellingGuzman** [comment]
Hey there @Sirjoseph94, I wasn't able to reproduce it before, I was wondering how does your `composer.json` looks like?

**Comment by Sirjoseph94** [comment]
Hello @WellingGuzman i just updated to the latest v.6.4.0 and here is my composer.json
`{
  "require": {
    "php": ">=5.6.0",
    "slim/slim": "2.6.2",
    "slim/extras": "dev-master",
    "twig/twig":  "1.*",
    "zendframework/zend-db": "dev-directus",
    "directus/migrations": "dev-master",
    "directus/sdk": "0.1.*"
    "league/flysystem": "^1.0",
    "swiftmailer/swiftmailer": "^5.4",
    "league/oauth2-google": "^2.0",
    "league/oauth2-github": "^2.0",
    "league/oauth2-facebook": "^2.0",
    "league/oauth1-client": "^1.7"
  },
  "require-dev": {
    "phpunit/phpunit": "~3.7.0"
  },
  "suggest": {
    "paragonie/random_compat": "Generates cryptographically more secure pseudo-random bytes"
  },
  "_require": {
    "rackspace/php-opencloud": "dev-master",
    "amazonwebservices/aws-sdk-for-php": "1.6.2",
    "aws/aws-sdk-php": "2.6.*@dev"
  },
  "autoload": {
    "psr-4": {
      "Directus\\": "api/core/Directus/",
      "Directus\\API\\Routes\\": "api/routes/",
      "Directus\\Installation\\": "installation/includes/",
      "Directus\\Customs\\Embed\\Provider\\": "customs/embeds/",
      "Directus\\Customs\\Hooks\\": "customs/hooks/",
      "Directus\\Customs\\Hasher\\": "customs/hashers/"
    },
    "files": [
      "api/core/functions.php"
    ]
  },
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/WellingGuzman/Slim-Extras.git"
    },
    {
      "type": "git",
      "url": "https://github.com/wellingguzman/zend-db"
    }
  ]
}
`

**Comment by WellingGuzman** [comment]
But that's the Directus `composer.json` is there a reason why you are adding the `sdk` into the Directus `composer.json`?

**Comment by Sirjoseph94** [comment]
do i have to create another composer.json for the sdk?. am adding the sdk to my project to make it easier for me to interface with the api

**Comment by WellingGuzman** [comment]
If you are using the sdk into another project outside from Directus, you must create a independent `composer.json` into another project (directory), otherwise you have access to data from within Directus, no in the same way though.

**Comment by WellingGuzman** [comment]
either way, if you want to use it there, you could probably recreate the autoload by running `composer dump-autoload`

**Comment by Sirjoseph94** [comment]
the directus folder is a sub folder in the project folder. am using the directus as an admin cms.

**Comment by WellingGuzman** [comment]
What are you trying to do? what `call.php` for?

**Comment by Sirjoseph94** [comment]
all i want is an easier and better way of GETting data from the directus API to the frontend while directus remains the backen. I don't ant to reinvent the wheel by creating my own codes to retrieve these data

it would be nice if there's some video tutorials to go with the docs though

**Comment by WellingGuzman** [comment]
It's all good. have it separate in its own project, into a separated `composer.json` and try it that way and see if it works.

**Comment by Sirjoseph94** [comment]
alright. thanks for prompt response

**Comment by WellingGuzman** [comment]
@mbuchser it seems you are going to the same approach, am I correct?

**Comment by Sirjoseph94** [comment]
thanks @WellingGuzman it worked.

**Comment by mbuchser** [comment]
Thanks for the updates. 

i've tried the same as @Sirjoseph94 and added an php file (like his call.php) into the directus main directory, to test if i can retreive some items, and for this purpose i configured the composer.json in the directus main directory. 

So in order to make it work:
1. create an folder within the directus main directory (eg. myapp - http://localhost/directus/myapp)
2. inside the new (myapp) folder create a "composer.json" which has to look like this:
{
  "require": {
    "directus/sdk": "0.1.*"
  },
  "minimum-stability": "dev",
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/wellingguzman/zend-db"
    }
  ]
}
3. execute "composer install"
4. create your own php file (eg test.php) within the new folder (myapp) with something like:
<?php
<require_once 'vendor/autoload.php';

$client = \Directus\SDK\ClientFactory::create('yourtokengoeshere', [
    // Directus API Path without its version
    'base_url' => 'http://localhost/yourdirectusdirectory/',
    'version' => '1.1' // Optional - default 1
]);

$articles = $client->getItems('personen');
//var_dump($articles);
foreach($articles as $article) {
    echo $article->vorname . '<br>';
}
?>
works for me with directus6.4 - BUT the version parameter has to match the api version installed (eg 1.1) otherwhise you get something like:
Fatal error: Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `GET http://localhost/directus/api/1/tables/person/rows` resulted in a `404 Not Found`  

hope that helps.

**Comment by WellingGuzman** [comment]
Thanks for the update, I will improve the errors to a more friendly messages. follow this issue in #15

**Comment by Alfier** [comment]
Is there a way to make things work without composer?
I keep getting a fatal error like the OP

**Comment by benhaynes** [comment]
We have a `build` branch that has all the dependencies included – perhaps this is what you're looking for?

@WellingGuzman – any additional thoughts on this?

**Comment by WellingGuzman** [comment]
For the SDK we do not have `build` which now that I think about it it should.

@Alfier How are you trying to install it? I could help you while I try to create a build branch some time this week.

**Comment by Alfier** [comment]
An all-ready build with SDK included would be wonderful (also, I think it's a pretty straightforward feature to implement asap).
As for now, I'm trying to install everything the old fashioned way, ftp commit and code every dependence, but indeed something is out of my league.
If you say the build branch could be online some time this week I would happily wait, thank you.

**Comment by benhaynes** [comment]
Sounds good – @WellingGuzman how long would it take to create a `build` branch for the PHP SDK? Is that something that we can get done today?

**Comment by Alfier** [comment]
Any news for the new Directus version and the SDK-ready build?
