### ISSUE TITLE
Problem with getColumns() on textarea/textinputs

### ISSUE THREAD

**Issue by npinansky** [directus/directus-sdk-php#13]
I am getting an "Invalid argument supplied for foreach()" in vendor/directus/sdk/src/Response/Entry.php:60 ( in  Directus\SDK\Response\EntryCollection::__construct() )  when calling a getColumns() on any table that has textarea/textinput columns. 

The reason for this appears to be that they have "rows" attributes and in Directus\SDK\Response\Entry::__construct() there is this conditional:
`        foreach($data as $field => $value) {
            if (isset($value['rows']) || (isset($value['data']) && ArrayUtils::isNumericKeys($value['data']))) {
                $this->data[$field] = new EntryCollection($value);
`

it looks like it should be something more like this:
`
           if ((isset($value['rows']) &&
                    (array_key_exists('id', $value) && ! in_array($value['id'], ['textarea','textinput'])))
                || (isset($value['data']) && ArrayUtils::isNumericKeys($value['data']))) {
                $this->data[$field] = new EntryCollection($value);
`

**Comment by WellingGuzman** [comment]
Old issue, wasn't able to replicate back then, still not able. I will close this and pretended it was fixed on 1.0.0, if this still happen and provide a steps to reproduce this issue I will re-open this ticket.
