### ISSUE TITLE
Unclear how to set a many-to-one field

### ISSUE THREAD

**Issue by wittwerch** [directus/directus-sdk-php#16]
Directus version: https://github.com/directus/directus/commit/fabd5479836c0b06a0ef20f5916b92e5a06e8987
SDK version: 0.1.2

I'm trying to create a topic over the API and set the owner to a previously created user.

![screen shot 2017-08-16 at 08 12 26](https://user-images.githubusercontent.com/1575445/29349496-aa725ed2-825a-11e7-8ea3-35ce468f7f71.png)

Creating the user
````
$john = $client->createUser([
    'email' => 'john@foo.com',
    'first_name' => 'John',
    'last_name' => 'Owner',
    'password' => '1234',
    'group' => '3',
    'token' => 'token3'
]);

Try 1
````
$gossip = $client->createItem('topics', [
    'title' => 'Gossip',
    'owner' => $john
]);
````
Try 2
````
$gossip = $client->createItem('topics', [
    'title' => 'Gossip',
    'owner' => $john->id
]);
````

Both result in the owner to be NULL.
````
|  3 | Gossip    | NULL                            |     NULL |          1 |
````

**Comment by WellingGuzman** [comment]
Hey @wittwerch, after couple of tries, I still get the correct result using the example below:

```php
$john = $client->createUser([
    'email' => 'john@foo.com',
    'first_name' => 'John',
    'last_name' => 'Owner',
    'password' => '1234',
    'group' => '3',
    'token' => 'token3'
]);
```

```php
$gossip = $client->createItem('topics', [
  'title' => 'Gossip',
  'owner' => $john->id
]);
```

can you share an example schema that I can use? are you using API (using token) or Direct connection (using mysql credentials)?

**Comment by WellingGuzman** [comment]
Due to lack of activity I'm going to close this ticket.
