### ISSUE TITLE
Fatal error: Uncaught exception 'Directus\SDK\Exception\UnauthorizedRequestException' with message 'Unauthorized GET Request to

### ISSUE THREAD

**Issue by Zilus** [directus/directus-sdk-php#17]
I have a 6.3 directus installed as backend.
I was connecting to the api via the php sdk, but now I can't. The error is:

```Fatal error: Uncaught exception 'Directus\SDK\Exception\UnauthorizedRequestException' with message 'Unauthorized GET Request to http://server/admin/api/1.1/tables/meta/rows/1' in /home/cav/public_html/demo/vendor/directus/sdk/src/BaseClientRemote.php:292 Stack trace: #0 /home/cav/public_html/demo/vendor/directus/sdk/src/ClientRemote.php(77): Directus\SDK\BaseClientRemote->performRequest('GET', 'tables/meta/row...', Array) #1 /home/cav/public_html/demo/config.php(16): Directus\SDK\ClientRemote->getItem('meta', 1) #2 /home/cav/public_html/demo/common/header.php(2): include('/home/cavdiseno...') #3 /home/cav/public_html/demo/index.php(1): include('/home/cavdiseno...') #4 {main} thrown in /home/cav/public_html/demo/vendor/directus/sdk/src/BaseClientRemote.php on line 292```

My composer.json:
```
{
    "require": {
        "directus/sdk": "^0.1.1"
    },
    "minimum-stability": "dev",
    "repositories": [
      {
        "type": "git",
        "url": "https://github.com/wellingguzman/zend-db"
      }
    ],
    "license": "MIT",
    "authors": [
        {
            "name": "Oscar Azpeitia",
            "email": "neozilus@gmail.com"
        }
    ]
}
```

I don't know, but I think the problem lies in this (while running composer install):
```
  - Installing directus/collection (dev-version/6.4 8e53f6c)
    Cloning 8e53f6ca3d227e9bfc97df92e6a1362cba64d290
```

My composer.json (backend):
```
{
"require": {
    "php": ">=5.5.0",
    "slim/slim": "2.3.2",
    "slim/extras": "dev-develop",
    "twig/twig":  "1.*",
    "directus/migrations": "dev-master",
    "directus/permissions": "0.9.*@dev",
    "directus/database": "~0.1.3",
    "league/flysystem": "^1.0",
    "swiftmailer/swiftmailer": "^5.4"
  },
...
```

**Comment by WellingGuzman** [comment]
Hey @Zilus is still a issue, it seems to be a issue with the old version, please try using `1.0.0`, otherwise let me know and I will re-open the ticket.
