### ISSUE TITLE
App can't find tables

### ISSUE THREAD

**Issue by thenatefleming** [directus/directus-sdk-php#18]
Hi, I have an application that is attempting to pull data from a directus install and I keep getting the same error message in my application's console:

`{message: "Unable to find the table "my_data"}`

I am currently working locally with my api endpoint being:
`http://localhost:8888/cms/api/1.1/tables/directus_users` and when I hit that in the browser I see my json as expected, but apparently it can't find the tables that clearly exist. I've checked the database to ensure the table is there and not just showing in my directus GUI and have made sure that read permissions are set properly. Can someone please help me retrieve my data?
Thanks.

**Comment by rijkvanzanten** [comment]
How do you try fetching this data from the SDK? Do you have example code / a simple schema maybe so we can reproduce this?

**Comment by WellingGuzman** [comment]
Also, is this table being managed by directus?

**Comment by WellingGuzman** [comment]
Due to lack of activity I'm going to close this ticket.
