### ISSUE TITLE
500 error after following instructions

### ISSUE THREAD

**Issue by foggy-hazard** [directus/directus-sdk-php#19]
When I try to follow the instructions in the readme and add these lines to the composer.json file and then run composer update I get a 500 error when trying to access Directus.

Is this a known problem?
Am I missing something, is there another file where I should be editing the first part instead of the composer.json in the root directus directory?

**Comment by WellingGuzman** [comment]
Hey @foggy-hazard can you show us how are you accessing Directus? can you provide some example code?

**Comment by foggy-hazard** [comment]
Hi @WellingGuzman! I’m using a LAMP setup on ubuntu 16.04.
The only thing that I changed was the composer.json file based on the readme info in this repo, and then ran composer update.

This is how my composer.json looks like after changing it:
https://codeshare.io/foggy-h

Is there another place I should be adding this then in the composer.json file?

**Comment by WellingGuzman** [comment]
You shouldn't be adding the SDK into Directus, the SDK is meant to work as standalone, outside the Directus directory and composer.json

All the steps described in the README are for a new composer file in a new directory outside Directus directory.

I'm closing this as this doesn't seem like a bug to the SDK, but rather a confusion on how to use it.

Here is an example: https://github.com/directus/webapp-example
