### ISSUE TITLE
allow guzzle 6.0 ?

### ISSUE THREAD

**Issue by twoSeats** [directus/directus-sdk-php#2]
I assume that guzzle 5.0 is specified in composer.json because of the desire to allow this package to be used with php 5.4
As some may already have left that behind and be using 6.0, could you allow either to be installed? something like ~5.0|~6.0

The problem:
![screenshot from 2016-12-07 11 55 20](https://cloud.githubusercontent.com/assets/536306/20963171/fd6e24ba-bc74-11e6-8e83-baf6f18d9197.jpeg)

**Comment by WellingGuzman** [comment]
Hey @twoSeats, I'm sorry I just noticed this ticket.

I will take a look into it, and I will get back to you sometime.

Thanks.

**Comment by WellingGuzman** [comment]
Hey @twoSeats, kind of a bit late, but better sooner than later.

I've updated the SDK to support Guzzle 6, let me know if it works for you.

**Comment by twoSeats** [comment]
@WellingGuzman thanks, I'll let you know!
