### ISSUE TITLE
Wrong logic for avatar_file_id

### ISSUE THREAD

**Issue by rande** [directus/directus-sdk-php#21]
Hello,

I am writing a script to import users to directus. And there is an issue with the ``avatar_file_id`` field. The documentation stated the api expected an ``integer`` however the code expect to be a ``File`` object.

https://github.com/directus/directus-sdk-php/blob/6c282bac9e18eb998da87fea370916e9dd53086e/src/AbstractClient.php#L88-L90

https://github.com/directus/directus-sdk-php/blob/6c282bac9e18eb998da87fea370916e9dd53086e/src/AbstractClient.php#L61-L78

Commented the related lines, seems to works, however I am not sure about any side effet.

**Comment by WellingGuzman** [comment]
I will take a look, it should take the `Integer` and convert it into a `File` object (under the hood).
