### ISSUE TITLE
createItem does not create an item but returns a list of all items

### ISSUE THREAD

**Issue by arthurzaczek** [directus/directus-sdk-php#22]
Creating a item in directus works, but not from the php-sdk. It does not reutrn any error but returns a list of all items. According to the docmentation it should return the created item.

```
directus/sdk => 1.0.0
directus => v6.4.4
api version => 1.1
```

here is my example code:

```
$client = \Directus\SDK\ClientFactory::create($apiKey, [
    'base_url' => $url,
    'version' => '1.1'
]);
...
var_dump($this->client->createItem('leihplattform', [ 
    'status' => 1, 
    'Was' => 'test',
    'wer' => 'arthur',
    'beschreibung' => 'xyz'
]));
```

**Comment by WellingGuzman** [comment]
@arthurzaczek I was unable to reproduce this issue, did you manage to solve it? could you please share the schema of that table?

**Comment by arthurzaczek** [comment]
I ended up using a simple online excel and uninstalled my directus installation.
