### ISSUE TITLE
Cannot install due to missing dependency

### ISSUE THREAD

**Issue by taxaos** [directus/directus-sdk-php#26]
```
composer require directus/sdk
Using version ^1.0 for directus/sdk
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - directus/database 1.0.0 requires zendframework/zend-db dev-directus -> no matching package found.
    - directus/sdk 1.0.0 requires directus/database ^1.0.0 -> satisfiable by directus/database[1.0.0].
    - Installation request for directus/sdk ^1.0 -> satisfiable by directus/sdk[1.0.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

As you can see in the output, the `directus/database/` needs `zendframework/zend-db` with version `dev-directus` which is not available in the original Zend Repository. 

How to fix? Wanna use this client :)

**Comment by WellingGuzman** [comment]
Hey @taxaos, how your composer.json looks like?

I created a fork from zend-db to fix some issues we were experiencies with ZendDB.

You need to add the code below into your `composer.json`, this repository is not published to packagist.

```json
"repositories": [{
    "type": "git",
    "url": "https://github.com/wellingguzman/zend-db"
}]
```

**Comment by taxaos** [comment]
Hello @WellingGuzman,

thanks for the information. I've attached a PR to this repo to reflect this in install (see https://github.com/directus/directus-sdk-php/pull/27)

**Comment by BennerGe** [comment]
I've got also problems to install the SDK.
Using the following `composer.json`
```{
  "require": {
    "directus/sdk": "0.9.*"
  },
  "repositories": [{
    "type": "git",
    "url": "https://github.com/wellingguzman/zend-db"
  }]
}
```
leads to this error:
```
The requested package directus/sdk could not be found in any version, there may be a typo in the package name.
```

When changing the required version of the SDK to `"directus/sdk": "1.0.0"` the error as described above by @taxaos occurs.

**Comment by WellingGuzman** [comment]
Hey @BennerGe can you try adding `"minimum-stability": "dev"`?

Example:
```json
{
  "require": {
    "directus/sdk": "0.9.*"
  },
  "minimum-stability": "dev",
  "repositories": [{
    "type": "git",
    "url": "https://github.com/wellingguzman/zend-db"
  }]
}
```

Or use the version 1.0.0 which is the latest version.

**Comment by BennerGe** [comment]
Adding `minimum-stability` worked, this is also necessary to install version `1.0.0`

**Comment by WellingGuzman** [comment]
Thanks @BennerGe, I will add it to the readme!
