### ISSUE TITLE
How to query specific items in a table using PHP SDK?

### ISSUE THREAD

**Issue by rahulhopin** [directus/directus-sdk-php#31]
I am only able to find getItems api. How can we do where/orderby queries with this SDK ?

**Comment by WellingGuzman** [comment]
Hey @rahulhopin,

You can read [here about parameters](https://github.com/directus/api-docs/blob/615986dc79f80a925706f9849568e01af1ecdf8c/SDKs/php-sdk.md#get-parameters) in the php SDK.

Here have a bit more details about filtering: https://github.com/directus/api-docs/blob/1.1/overview/filters.md.

As this is not an actual SDK issue, I will close it. We can keep the conversation if you still have any question.

**Comment by Muphet** [comment]
how do you implement multiple filters within php sdk?
`'filters' => ['filter1' => ['table'=>'value'],
'filter2' => ['table'=>'value']];`
will return only elements that both filters apply to. How do you add OR to it?

**Comment by benhaynes** [comment]
@WellingGuzman ??
