### ISSUE TITLE
When creating user, password should not be hashed?

### ISSUE THREAD

**Issue by tchai81** [directus/directus-sdk-php#32]
According to this line here:-
https://github.com/directus/directus-sdk-php/blob/dab3b083eaad0526fa5cc860205f953332f71ea9/src/AbstractClient.php#L85

Password that is being send over to directus server should not be hashed? 

Error response from directus server while creating user using SDK:-
{"success":false,"error":{"message":"Incorrect email or password"},"message":"User has no token"}

It will work after i've commented out the stated line.

**Comment by WellingGuzman** [comment]
Hey @tchai81, are you connecting via de API or directly to a database? The API should get a plain text while the db should hash the password before insert it to the database.

**Comment by tchai81** [comment]
Hey @WellingGuzman,

Thanks for your reply. :)

I'm connecting via the API. I tried to debug through the code, it seems i'm calling the ClientRemote.php:-

https://github.com/directus/directus-sdk-php/blob/dab3b083eaad0526fa5cc860205f953332f71ea9/src/ClientRemote.php#L202

The processData function is calling the processData function in AbstractClient, which in turn is calling the processDataOnDirectusUsers.

The SDK apparently will still hashed the password even though you are connecting via the API.

**Comment by WellingGuzman** [comment]
You are correct, the client should not hash the password when connection through the API.
