### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by flrrrhoffpauir** [directus/directus-sdk-php#4]
'composer require directus/sdk' gives the following output

Problem 1
    - directus/database 0.1.0 requires zendframework/zend-db dev-directus -> no matching package found.
    - directus/sdk 0.9.x-dev requires directus/database 0.1.* -> satisfiable by directus/database[0.1.0].
    - Installation request for directus/sdk ^0.9.0@dev -> satisfiable by directus/sdk[0.9.x-dev].

There is no dev-directus version of zend-db

**Comment by WellingGuzman** [comment]
Hello @flrrrhoffpauir, thanks for reporting this.

I will have to revert this, we started using an a different branch that we work work to support spaces and dashes on columns, but it's not yet on their code, but while I'm reverting, you can do this to fix the problem.

On your `composer.json` add these lines:

```
"repositories": [
    {
      "type": "git",
      "url": "https://github.com/wellingguzman/zend-db"
    }
  ]
```

Sorry for this problem we are in kind of a beta time, but we are releasing the SDK stable soon enough.

I will get back as soon it's fixed.

**Comment by flrrrhoffpauir** [comment]
Thank you very much for the quick reply! That worked and I am good to go.

Thanks,
Junie

**Comment by WellingGuzman** [comment]
Glad to hear.

I've updated the dependencies and tagged some versions of the dependencies.

I'm closing this ticket, if this happens again let us know.
