### ISSUE TITLE
getItems based on status is ignored

### ISSUE THREAD

**Issue by flrrrhoffpauir** [directus/directus-sdk-php#7]
```
$entry = $this->directus->getItems('customers', [
	'status' => ['1'],
	'filters' => [
		'email' => ['eq' => $email],
	],
]);
```

I'm trying to get items that have not been deleted, but deleted items are still returned. I have also tried using filters on the 'active' column but even the deleted records are set to 1

**Comment by WellingGuzman** [comment]
hey @flrrrhoffpauir thanks for reporting this.

I will check this out in a couple of minutes, I will get back as soon as I get a fix.

**Comment by WellingGuzman** [comment]
Hey @flrrrhoffpauir, I want to know if you are using direct connection to the database or an Directus API?

In the meantime this should work:

```
$entry = $this->directus->getItems('customers', [
	'filters' => [
                'active' => 1,
		'email' => ['eq' => $email],
	],
]);
```

**Comment by flrrrhoffpauir** [comment]
@WellingGuzman I am using a direct connection to a database.

The other issue is that the deleted records still have 'active' set to 1, so using the filters doesn't work either

**Comment by WellingGuzman** [comment]
hey @flrrrhoffpauir, deleting item is not changing `active` to anything? I'd have to check that out.

**Comment by flrrrhoffpauir** [comment]
@WellingGuzman correct. If it would help, I can paste a response with the Entry Collection and Entry object data (which specifically for me is returning 2 Entry objects. 1 active and 1 deleted but with both having active set to 1)

**Comment by flrrrhoffpauir** [comment]
@WellingGuzman have you been able to look into this? Is there a manual workaround to the database that I could apply for now?

**Comment by WellingGuzman** [comment]
Hey, sorry for the delay,

I tried to delete an item and it worked, I tried to fetch by status and it work, I'm connecting directly to the database.

Please show me the response data, also what is the hash of the sdk and directus/database installed by composer?

**Comment by WellingGuzman** [comment]
Hey @flrrrhoffpauir, This seems to be working now, If still happening to you let us know, I will try to fix it asap.
