### ISSUE TITLE
Fatal Error: Directus\Hook\Payload not found

### ISSUE THREAD

**Issue by davidpanaho** [directus/directus-sdk-php#8]
Apologies if I'm supposed to follow some kind of issue logging structure, this is my first post!

When using the database connection method outlined in the readme, the following error appears:

> Uncaught Error: Class 'Directus\Hook\Payload' not found in D:\xampp\htdocs\directus-front\vendor\directus\database\TableGateway\BaseTableGateway.php:1116 Stack trace: #0 D:\xampp\htdocs\directus-front\vendor\directus\database\TableGateway\BaseTableGateway.php(633): Directus\Database\TableGateway\BaseTableGateway->applyHook('table.select', Array, Array) #1 D:\xampp\htdocs\directus-front\vendor\directus\database\TableGateway\BaseTableGateway.php(601): Directus\Database\TableGateway\BaseTableGateway->executeSelect(Object(Zend\Db\Sql\Select), Array) #2 D:\xampp\htdocs\directus-front\vendor\directus\database\TableGateway\RelationalTableGateway.php(806): Directus\Database\TableGateway\BaseTableGateway->selectWith(Object(Zend\Db\Sql\Select)) #3 D:\xampp\htdocs\directus-front\vendor\directus\database\TableGateway\RelationalTableGateway.php(696): Directus\Database\TableGateway\RelationalTableGateway->loadItems(Array) #4 D:\xampp\htdocs\directus-front\vendor\directus\sdk\src\ClientLocal.php(96): Directus\Database\Table in D:\xampp\htdocs\directus-front\vendor\directus\database\TableGateway\BaseTableGateway.php on line 1116

I was able to remedy the issue by replacing the database folder with the one from the latest version of Directus (downloaded today).

Is this just a matter of updating the composer.json files? I noticed that  the "directus/directus" composer.json file requires a later version of "directus/database" and doesn't have any reference to "directus/hook" when compared to "directus/sdk".

**Comment by benhaynes** [comment]
Hey @davidpanaho – this might be caused by this hotfix, we'll update the docs accordingly:

https://github.com/directus/directus/issues/1418#issuecomment-298214929

**Comment by WellingGuzman** [comment]
Hey @davidpanaho,

I've fixed this, please try installing the version `0.1.2`, it should fix the issue.

**Comment by davidpanaho** [comment]
Just reinstalled and it all looks good, thanks!
