### ISSUE TITLE
Warning error when using createItem with spl_autoload_register

### ISSUE THREAD

**Issue by davidpanaho** [directus/directus-sdk-php#9]
I just want to preface this by saying this could be an issue with my implementation of `spl_autoload_register()`, as I have only recently started using it.

I'm using `spl_autoload_register()` to load my own namespaced classes. I'm also using composer to bring in directus-sdk-php. When trying to use `$client->createItem()`, I get the following errors: 

```
Warning: include(D:\xampp\htdocs\directus-test/Directus/Database/RowGateway/DirectusActivityRowGateway.php): failed to open stream: No such file or directory in D:\xampp\htdocs\directus-test\myAutoloader.php on line 13

Warning: include(): Failed opening 'D:\xampp\htdocs\directus-test/Directus/Database/RowGateway/DirectusActivityRowGateway.php' for inclusion (include_path='D:\xampp\php\PEAR') in D:\xampp\htdocs\directus-test\myAutoloader.php on line 13
```

I think these error messages are directly related to my usage of `spl_autoload_register()` because when I include my class without the autoloader, the errors disappear.

For testing purposes, I am able to use `$client->getItem()` without any problems, so the issue seems to be directly related to `$client->createItem()`.

I have no idea what file `DirectusActivityRowGateway.php` is but my suspicion is that composer's autoloader isn't able to find it and is quietly dealing with the issue. Then my autoloader also tries to open the file and fails. Then again, I could be way off base - I'm not sure of the internal workings with autoloaders.

Anyway, let me know if you need any further information.

**Comment by WellingGuzman** [comment]
Hey @davidpanaho, interesting issue, can you show me a snippet of code so I can use to reproduce this problem?

**Comment by davidpanaho** [comment]
Sure thing, here are my files:

**composer.json**
```
{
  "require": {
    "directus/sdk": "0.1.*"
  },
  "minimum-stability": "dev",
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/wellingguzman/zend-db"
    }
  ]
}
```

**index.php**
```
<?php

require('vendor/autoload.php');
require('myAutoloader.php');

use model\Api;

$api = new Api;
$client = $api->client;

// this works
$getTest = $client->getItem('test', 1);

echo '<pre>';
var_dump($getTest);
echo '</pre>';

// this throws error but stil works
$createTest = $client->createItem('test', [
	'active' => 1,
	'name' => 'hello again',
]);

echo '<pre>';
var_dump($createTest);
echo '</pre>';
```

**myAutoloader.php**
```
<?php

spl_autoload_register('my_autoloader');

function my_autoloader($class) {
	include (__DIR__ . '/' . str_replace('\\', '/', $class) . '.php');
}
```

**model/Api.php**
```
<?php

namespace model;

class Api
{
	private $config = [
	    'database' => [
	        'hostname' => 'localhost',
	        'username' => 'root',
	        'password' => '',
	        'database' => 'directus_test',
	        // Optional
	        // 'port' => 3306,
	        // 'charset' => 'utf8'
	    ],
	    'filesystem' => [
	        'root' => 'storage/uploads'
	    ]
	];

	public $client;

	public function __construct() {
		$this->client = \Directus\SDK\ClientFactory::create($this->config);
	}

}
```

**Comment by davidpanaho** [comment]
Sure thing, here are my files:

**composer.json**
```
{
  "require": {
    "directus/sdk": "0.1.*"
  },
  "minimum-stability": "dev",
  "repositories": [
    {
      "type": "git",
      "url": "https://github.com/wellingguzman/zend-db"
    }
  ]
}
```

**index.php**
```
<?php

require('vendor/autoload.php');
require('myAutoloader.php');

use model\Api;

$api = new Api;
$client = $api->client;

// this works
$getTest = $client->getItem('test', 1);

echo '<pre>';
var_dump($getTest);
echo '</pre>';

// this throws error but stil works
$createTest = $client->createItem('test', [
	'active' => 1,
	'name' => 'hello again',
]);

echo '<pre>';
var_dump($createTest);
echo '</pre>';
```

**myAutoloader.php**
```
<?php

spl_autoload_register('my_autoloader');

function my_autoloader($class) {
	include (__DIR__ . '/' . str_replace('\\', '/', $class) . '.php');
}
```

**model/Api.php**
```
<?php

namespace model;

class Api
{
	private $config = [
	    'database' => [
	        'hostname' => 'localhost',
	        'username' => 'root',
	        'password' => '',
	        'database' => 'directus_test',
	        // Optional
	        // 'port' => 3306,
	        // 'charset' => 'utf8'
	    ],
	    'filesystem' => [
	        'root' => 'storage/uploads'
	    ]
	];

	public $client;

	public function __construct() {
		$this->client = \Directus\SDK\ClientFactory::create($this->config);
	}

}
```

**Comment by davidpanaho** [comment]
Also, I forgot to mention this key point earlier: 

`$client->createItem()` still works in that the rows are being created in the database.

**Comment by davidpanaho** [comment]
I can confirm that the error is being thrown in my autoloader as I can suppress the error by sticking an **@** symbol in front of the include in **myAutoloader.php**:

```
function my_autoloader($class) {
	@include (__DIR__ . '/' . str_replace('\\', '/', $class) . '.php');
}
```

**Comment by WellingGuzman** [comment]
Hey @davidpanaho, this seems as a problem you are creating yourself, that seems a conflict with you autoload, that I'm sure you are aware of, but try to check if that path still exists first.

That's just my thought before testing your code, I will test it, but this is not part of a SDK issue.

I will try to help you in here, but I will close the ticket, and open if the problem it's actually the SDK.

**Comment by davidpanaho** [comment]
Thanks, any help would be appreciated. I understand it may be an issue with the way my autoloader works but the code I posted above is pretty much all the code I have written for this site - I created a bare setup just to test the issue.

Here is my folder structure:

* directus-test/ _(root folder)_
  * admin/ _(where directus has been installed)_
  * model/ _(contains api class)_
    * Api.php
  * storage/ _(storage folder created by directus)_
  * vendor/ _(contains vendor files from composer)_
  * index.php
  * myAutoloader.php
  * composer.json

Let me know if you need any other info from my end, hopefully you'll be able to spot where I'm going wrong!

**Comment by WellingGuzman** [comment]
hey @davidpanaho can which version of the SDK are you using? I'm going to test the same code you shared.

**Comment by davidpanaho** [comment]
I think I'm using 0.1.2, I downloaded it this morning using 0.1.* in my composer.json file.

**Comment by WellingGuzman** [comment]
@davidpanaho the issue is with your autoloader, it doesn't check if the class (filename) exists before trying to include it.

I will recommend to do that, or rather use composer autoload instead.

**Comment by davidpanaho** [comment]
Thank you for this! I'll implement a fix on my autoloader. Is there a reason why the warnings didn't show when using $client->getItem()? Thanks again

**Comment by WellingGuzman** [comment]
Because `getItem` doesn't use rowgateway, while `createItem` does to log the record creation activity.

**Comment by davidpanaho** [comment]
Ah cool. Thanks again!
